<?php declare(strict_types=1);
/**
 *
 * @author      deviget Core Team <contact@deviget.com>
 * @copyright   2023 deviget (https://deviget.com)
 * @license     https://deviget.com Copyright
 * @link        https://deviget.com
 *
 */

/** @var $block Magento\Framework\View\Element\Template */

?>

<a href="/profile-page" target="_self">
<img src="<?php echo $block->getViewFileUrl('Deviget_PromoBanners::images/pdp/sidebar.png'); ?>"
     alt="<?php echo __('Promo Banner')?>">
</a>
